import type { Project } from "@/types/projects";

const fullStackApps = [
  {
    key: "sparkverse",
    title: "Sparkverse",
    role: "Full Stack Developer",
    href: "https://sparkverse.in/",
    createdAt: "12/06/2026",
    updatedAt: "on going",
    client: "team",
    description:
      "A tech-focused news platform built to surface what is shaping the technology world — from emerging trends and AI to CEO insights, developer conversations, gaming, and the ideas driving the next wave of innovation.",
    tags: [
      "Next.js",
      "TypeScript",
      "Supabase",
      "PostgreSQL",
      "Tailwind CSS",
      "GSAP",
      "Vercel",
    ],
    keywords: [
      "tech-news",
      "technology",
      "tech-trends",
      "ai",
      "startups",
      "ceo-insights",
      "developer-news",
      "gaming",
      "innovation",
      "full-stack",
      "nextjs",
      "supabase",
      "postgresql",
    ],
  },

  {
    key: "six-teal-store",
    title: "Six Teal Store",
    role: "Full Stack Developer",
    createdAt: "30/08/2025",
    updatedAt: "26/07/2026",
    client: "team",
    href: "https://sixtealstore.vercel.app/",
    description:
      "A modern e-commerce platform designed around a smooth shopping experience, with product discovery, cart management, and interactive storefront experiences powered by a scalable full-stack architecture.",
    tags: [
      "Next.js",
      "TypeScript",
      "Supabase",
      "PostgreSQL",
      "Zustand",
      "Tailwind CSS",
      "GSAP",
      "Vercel",
    ],
    keywords: [
      "ecommerce",
      "online-store",
      "shopping",
      "product-catalog",
      "cart-management",
      "state-management",
      "zustand",
      "full-stack",
      "nextjs",
      "supabase",
      "postgresql",
      "responsive-ui",
    ],
  },

  {
    key: "cloak-shield-web",
    title: "Next Auth Cloak Shield",
    role: "Full Stack Developer",
    createdAt: "30/08/2025",
    updatedAt: "next",
    client: "team",
    href: "https://github.com/frenzzofficial/cloak-shield-web",
    description:
      "A secure authentication-focused web application built with Next.js and Hono, using Supabase and MySQL to handle identity, user data, and backend services with a clean full-stack architecture.",
    tags: [
      "Next.js",
      "TypeScript",
      "Hono",
      "Supabase",
      "MySQL",
      "Tailwind CSS",
      "Vercel",
    ],
    keywords: [
      "authentication",
      "authorization",
      "next-auth",
      "hono",
      "secure-auth",
      "user-management",
      "session-management",
      "backend-api",
      "full-stack",
      "nextjs",
      "supabase",
      "mysql",
    ],
  },
] satisfies Project[];

export default fullStackApps;
